# Declare variables to be passed into your templates.

ClusterEnv: dev
ClusterName: tarantool-crud

image:
  repository: vasiliyt/myapp
  tag: 0.2.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

Prometheus:
  port: 8081
  path: /metrics

RoleConfig:
  - RoleName: storage
    ReplicaCount: 2
    ReplicaSetCount: 2
    DiskSize: 1Gi
    CPUallocation: 0.25
    MemtxMemoryMB: 256
    RolesToAssign:
      - vshard-storage
      - vshard-router
      - metrics
      - crud-storage
      - crud-router
      - migrator
